-- MySQL Script generated by MySQL Workbench
-- Sat Dec  4 14:01:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema apps
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apps` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `apps` ;

-- -----------------------------------------------------
-- Table `apps`.`blood_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps`.`blood_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`));

-- -----------------------------------------------------
-- Table `apps`.`child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps`.`child` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `dni` VARCHAR(255) NULL DEFAULT NULL,
  `birthday` DATETIME NULL DEFAULT NULL,
  `blood_type_id` INT NULL DEFAULT NULL,
  `allergies` VARCHAR(255) NULL DEFAULT NULL,
  `cronic_diseases` VARCHAR(255) NULL DEFAULT NULL,
  `picture` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  
  CONSTRAINT `child_blood_type`
    FOREIGN KEY (`id`)
    REFERENCES `apps`.`blood_type` (`id`)
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `apps`.`check`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps`.`check` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `doctor` VARCHAR(255) NULL DEFAULT NULL,
  `finished` TINYINT(1) NULL DEFAULT NULL,
  `child_id` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `child_id` (`child_id` ASC) VISIBLE,
  CONSTRAINT `check_child`
    FOREIGN KEY (`child_id`)
    REFERENCES `apps`.`child` (`id`)
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `apps`.`check_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps`.`check_result` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `check_id` INT NULL DEFAULT NULL,
  `height` DECIMAL(5,2) NULL DEFAULT NULL,
  `weight` DECIMAL(5,2) NULL DEFAULT NULL,
  `head_size` DECIMAL(5,2) NULL DEFAULT NULL,
  `meds` VARCHAR(255) NULL DEFAULT NULL,
  `dose` VARCHAR(255) NULL DEFAULT NULL,
  `period` VARCHAR(255) NULL DEFAULT NULL,
  `study` VARCHAR(255) NULL DEFAULT NULL,
  `observations` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `check_id` (`check_id` ASC) VISIBLE,
  CONSTRAINT `check_result_check`
    FOREIGN KEY (`check_id`)
    REFERENCES `apps`.`check` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `apps`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `dni` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `mail` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `genere` VARCHAR(255) NULL DEFAULT NULL,
  `picture` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `apps`.`child_of`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps`.`child_of` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `child_id` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `child_id` (`child_id` ASC) VISIBLE,
  CONSTRAINT `child_of_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `apps`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `child_of_child`
    FOREIGN KEY (`child_id`)
    REFERENCES `apps`.`child` (`id`));


-- -----------------------------------------------------
-- Table `apps`.`child_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps`.`child_request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `original_user_id` INT NULL DEFAULT NULL,
  `new_user_id` INT NULL DEFAULT NULL,
  `request_date` DATETIME NULL DEFAULT NULL,
  `child_id` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `original_user_id` (`original_user_id` ASC) VISIBLE,
  INDEX `new_user_id` (`new_user_id` ASC) VISIBLE,
  CONSTRAINT `child_request_ibfk_1`
    FOREIGN KEY (`original_user_id`)
    REFERENCES `apps`.`user` (`id`),
  CONSTRAINT `child_request_ibfk_2`
    FOREIGN KEY (`new_user_id`)
    REFERENCES `apps`.`user` (`id`));


-- -----------------------------------------------------
-- Table `apps`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps`.`notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `avatar` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `unread` TINYINT(1) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `notification_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `apps`.`user` (`id`));


-- -----------------------------------------------------
-- Table `apps`.`password_reset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps`.`password_reset` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(255) NULL DEFAULT NULL,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `finished` TINYINT(1) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `apps`.`study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps`.`study` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `child_id` INT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `doctor` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `finished` TINYINT(1) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `child_id` (`child_id` ASC) VISIBLE,
  CONSTRAINT `study_child`
    FOREIGN KEY (`child_id`)
    REFERENCES `apps`.`child` (`id`)
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `apps`.`study_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps`.`study_result` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `study_id` INT NULL DEFAULT NULL,
  `observations` VARCHAR(255) NULL DEFAULT NULL,
  `files` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `study_id` (`study_id` ASC) VISIBLE,
  CONSTRAINT `study_result_study`
    FOREIGN KEY (`study_id`)
    REFERENCES `apps`.`study` (`id`));


-- -----------------------------------------------------
-- Table `apps`.`vaccine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps`.`vaccine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `child_id` INT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `doctor` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `received` TINYINT(1) NULL DEFAULT NULL,
  `dosis` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `child_id` (`child_id` ASC) VISIBLE,
  CONSTRAINT `vaccine_child`
    FOREIGN KEY (`child_id`)
    REFERENCES `apps`.`child` (`id`)
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `apps`.`vaccine_calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps`.`vaccine_calendar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vaccine` VARCHAR(255) NULL DEFAULT NULL,
  `dosis` VARCHAR(255) NULL DEFAULT NULL,
  `months_min` INT NULL DEFAULT NULL,
  `months_max` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
